### ISSUE TITLE
Link image "Xe điều khiển bằng smart phone" bị lỗi, không hiển thị được

### ISSUE THREAD

**Issue by Khuuxuanngoc** [MinhKhanh614/Robot-Chasiss-4WD-Car-R1#1]
![image](https://github.com/MinhKhanh614/Robot-Chasiss-4WD-Car-R1/assets/8817696/a45c1994-2028-4141-8464-3c6f34363d51)

**Comment by MinhKhanh614** [comment]
![Uploading Screenshot_14-5-2024_173435_github.com.jpeg…]()

**Comment by MinhKhanh614** [comment]
![Screenshot_14-5-2024_173435_github com](https://github.com/MinhKhanh614/Robot-Chasiss-4WD-Car-R1/assets/167750602/213c4059-3627-4aa0-a719-4fb900e16119)
